# Generated by Django 6.0.7 on 2026-07-14 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='chief_complaint',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='notes',
        ),
    ]
