# Generated by Django 6.0.7 on 2026-07-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_remove_visit_chief_complaint_remove_visit_notes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='visit',
            old_name='diagnosis',
            new_name='comments',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='treatment',
        ),
        migrations.AddField(
            model_name='visit',
            name='general_health',
            field=models.CharField(default='Good', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='visit',
            name='on_diet',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='on_drugs',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
