# Generated by Django 6.0.7 on 2026-07-14 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vital',
            name='diastolic',
        ),
        migrations.RemoveField(
            model_name='vital',
            name='pulse',
        ),
        migrations.RemoveField(
            model_name='vital',
            name='respiratory_rate',
        ),
        migrations.RemoveField(
            model_name='vital',
            name='spo2',
        ),
        migrations.RemoveField(
            model_name='vital',
            name='systolic',
        ),
        migrations.RemoveField(
            model_name='vital',
            name='temperature',
        ),
    ]
